name: qupai
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^3.0.7
  # 本地存储：https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^0.5.3+4
  # https://pub.dev/packages/oktoast#-readme-tab-
  oktoast: ^2.2.0
  # 权限检查、请求   https://pub.flutter-io.cn/packages/permission_handler#-installing-tab-
  permission_handler: ^5.0.0+hotfix.5
  # package_info: 获取APP版本信息：https://pub.flutter-io.cn/packages/package_info#-readme-tab-
  package_info: ^0.4.0+6
  # 用于打开网页、拨打电话、发短信、发邮件：https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^5.1.6
  # PageView上面等圆点  https://pub.flutter-io.cn/packages/page_view_indicator#-installing-tab-
  page_view_indicator: ^2.0.2
  # https://pub.dartlang.org/packages/crypto#-installing-tab-  md5加密
  crypto: ^2.1.3
  # 网络缓存图片  https://pub.flutter-io.cn/packages/cached_network_image#-installing-tab-
  cached_network_image: ^2.0.0-rc
  # Use with the CupertinoIcons class for iOS style icons.    https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^0.1.2
  # https://pub.dev/packages/json_annotation#-installing-tab-
  json_annotation: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_webview_plugin: ^0.3.11
  # 显示html文本   https://pub.flutter-io.cn/packages/flutter_html
  flutter_html: ^0.11.0
  charts_flutter: ^0.8.1
  rxdart: ^0.22.6
  #https://github.com/best-flutter/flutter_swiper/blob/master/pubspec.yaml
  flutter_swiper: ^1.1.6
  marquee_flutter: ^0.1.2
  # 下拉刷新上拉加载  https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.1.3
  # 选择器   https://pub.dartlang.org/packages/image_picker
  image_picker: ^0.6.3+1
  # 图片压缩  https://github.com/OpenFlutter/flutter_image_compress
  flutter_image_compress: ^0.6.3
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  # 分享  https://pub.flutter-io.cn/packages/share#-installing-tab-
  share: ^0.6.3+5
  image_gallery_saver: ^1.2.2
  date_format: ^1.0.8
  #侧滑删除  https://github.com/fluttercandies/left-scroll-actions
  left_scroll_actions: any
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.3.2
  #字符串
  sprintf: "^4.0.2"
  photo_view: ^0.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  # https://pub.dev/packages/json_serializable#-installing-tab-
  json_serializable: ^3.2.3



  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/arclist/
    - region.json